import { CouponAppliesTo } from '../../src/modules/domains/coupon/domain/enums/coupon-applies-to.enum';
import { CouponMinOrderType } from '../../src/modules/domains/coupon/domain/enums/coupon-min-order-type.enum';
import { CouponType } from '../../src/modules/domains/coupon/domain/enums/coupon-type.enum';

export type CouponSeed = {
  shopName: string;
  code: string;
  type: CouponType;
  appliesTo: CouponAppliesTo;
  appliesProductTitles?: string[];
  amountOff?: number;
  percentOff?: number;
  maxUses: number;
  maxUsesPerUser: number;
  minOrderType: CouponMinOrderType;
  minOrderValue?: number;
  minProducts?: number;
  isActive: boolean;
  isAutoSale: boolean;
  startDate: string;
  endDate: string;
};

export const couponSeeds: CouponSeed[] = [
  {
    shopName: 'Olive Atelier',
    code: 'OLIVE-FS',
    type: CouponType.FREE_SHIP,
    appliesTo: CouponAppliesTo.ALL,
    maxUses: 100,
    maxUsesPerUser: 3,
    minOrderType: CouponMinOrderType.NUMBER_OF_PRODUCTS,
    minProducts: 2,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Olive Atelier',
    code: 'OLIVE-FA',
    type: CouponType.FIXED_AMOUNT,
    appliesTo: CouponAppliesTo.SPECIFIC,
    appliesProductTitles: ['Canvas Market Tote'],
    amountOff: 8,
    maxUses: 75,
    maxUsesPerUser: 2,
    minOrderType: CouponMinOrderType.ORDER_TOTAL,
    minOrderValue: 40,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Olive Atelier',
    code: 'OLIVE-PC11',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.ALL,
    percentOff: 11,
    maxUses: 120,
    maxUsesPerUser: 3,
    minOrderType: CouponMinOrderType.ORDER_TOTAL,
    minOrderValue: 60,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Olive Atelier',
    code: 'OLIVE-PC',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.ALL,
    percentOff: 10,
    maxUses: 999,
    maxUsesPerUser: 5,
    minOrderType: CouponMinOrderType.NONE,
    isActive: true,
    isAutoSale: true,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Olive Atelier',
    code: 'OLIVE-PC-OIS',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.SPECIFIC,
    appliesProductTitles: ['Linen Weekend Dress'],
    percentOff: 14,
    maxUses: 999,
    maxUsesPerUser: 5,
    minOrderType: CouponMinOrderType.NONE,
    isActive: true,
    isAutoSale: true,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Reed Workshop',
    code: 'REED-FS',
    type: CouponType.FREE_SHIP,
    appliesTo: CouponAppliesTo.ALL,
    maxUses: 100,
    maxUsesPerUser: 3,
    minOrderType: CouponMinOrderType.NUMBER_OF_PRODUCTS,
    minProducts: 2,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Reed Workshop',
    code: 'REED-FA',
    type: CouponType.FIXED_AMOUNT,
    appliesTo: CouponAppliesTo.SPECIFIC,
    appliesProductTitles: ['Walnut Desk Headphones Stand'],
    amountOff: 6,
    maxUses: 80,
    maxUsesPerUser: 2,
    minOrderType: CouponMinOrderType.ORDER_TOTAL,
    minOrderValue: 30,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Reed Workshop',
    code: 'REED-PC11',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.ALL,
    percentOff: 11,
    maxUses: 120,
    maxUsesPerUser: 3,
    minOrderType: CouponMinOrderType.ORDER_TOTAL,
    minOrderValue: 60,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Reed Workshop',
    code: 'REED-PC',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.ALL,
    percentOff: 12,
    maxUses: 999,
    maxUsesPerUser: 5,
    minOrderType: CouponMinOrderType.NONE,
    isActive: true,
    isAutoSale: true,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Reed Workshop',
    code: 'REED-PC-OIS',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.SPECIFIC,
    appliesProductTitles: ['Studio Pullover Hoodie'],
    percentOff: 15,
    maxUses: 999,
    maxUsesPerUser: 5,
    minOrderType: CouponMinOrderType.NONE,
    isActive: true,
    isAutoSale: true,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Sage Studio',
    code: 'SAGE-FS',
    type: CouponType.FREE_SHIP,
    appliesTo: CouponAppliesTo.ALL,
    maxUses: 100,
    maxUsesPerUser: 3,
    minOrderType: CouponMinOrderType.NUMBER_OF_PRODUCTS,
    minProducts: 2,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Sage Studio',
    code: 'SAGE-FA',
    type: CouponType.FIXED_AMOUNT,
    appliesTo: CouponAppliesTo.SPECIFIC,
    appliesProductTitles: ['Minimal Horizon Print'],
    amountOff: 7,
    maxUses: 80,
    maxUsesPerUser: 2,
    minOrderType: CouponMinOrderType.ORDER_TOTAL,
    minOrderValue: 35,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Sage Studio',
    code: 'SAGE-PC11',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.ALL,
    percentOff: 11,
    maxUses: 120,
    maxUsesPerUser: 3,
    minOrderType: CouponMinOrderType.ORDER_TOTAL,
    minOrderValue: 60,
    isActive: true,
    isAutoSale: false,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Sage Studio',
    code: 'SAGE-PC',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.ALL,
    percentOff: 9,
    maxUses: 999,
    maxUsesPerUser: 5,
    minOrderType: CouponMinOrderType.NONE,
    isActive: true,
    isAutoSale: true,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
  {
    shopName: 'Sage Studio',
    code: 'SAGE-PC-OIS',
    type: CouponType.PERCENTAGE,
    appliesTo: CouponAppliesTo.SPECIFIC,
    appliesProductTitles: ['Oak Side Table'],
    percentOff: 13,
    maxUses: 999,
    maxUsesPerUser: 5,
    minOrderType: CouponMinOrderType.NONE,
    isActive: true,
    isAutoSale: true,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
  },
];
