export const SHOP_PRODUCT_LIST_DEFAULT_PAGE = 1;
export const SHOP_PRODUCT_LIST_DEFAULT_LIMIT = 20;
export const SHOP_PRODUCT_LIST_MAX_LIMIT = 50;

export const PRODUCT_PUBLIC_LIST_DEFAULT_PAGE = 1;
export const PRODUCT_PUBLIC_LIST_DEFAULT_LIMIT = 12;
export const PRODUCT_PUBLIC_LIST_MAX_LIMIT = 50;

export const SHOP_PRODUCT_REVIEW_LIST_DEFAULT_PAGE = 1;
export const SHOP_PRODUCT_REVIEW_LIST_DEFAULT_LIMIT = 20;
export const SHOP_PRODUCT_REVIEW_LIST_MAX_LIMIT = 50;
